#!/bin/bash

MVN_VERSION="$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null)"

if [ "$MVN_VERSION" == "${GIT_VERSION:1}" ]; then
  echo "true"
else
  echo "false"
fi
