#!/bin/bash

MVN_VERSION="$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null)"

cp target/statique-$MVN_VERSION-javadoc.jar target/statique-javadoc.zip
